steps:
  # Linting
  - name: 'python:3.9'
    dir: 'nginx-flask-mongo/flask'
    entrypoint: 'pip'
    args: ['install', 'pyflakes', 'mypy', 'black']
  - name: 'python:3.9'
    dir: 'nginx-flask-mongo/flask'
    entrypoint: 'pyflakes'
    args: ['.']
  - name: 'python:3.9'
    dir: 'nginx-flask-mongo/flask'
    entrypoint: 'mypy'
    args: ['.']
  - name: 'python:3.9'
    dir: 'nginx-flask-mongo/flask'
    entrypoint: 'black'
    args: ['.', '--check']

  # Build the Flask image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'nginx-flask-mongo/flask'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-backend', '.']

  # Push the Flask image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-backend']

  # Build the Nginx image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'nginx-flask-mongo'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-frontend', '-f', 'nginx.Dockerfile', '.']

  # Push the Nginx image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-frontend']

# Export logs to Cloud Storage
logsBucket: 'gs://440019-cloud-build-logging'