steps:
  # Build the Flask backend image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'nginx-flask-mongo/flask'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-backend:$COMMIT_SHA', '.']

  # # Lint the Flask backend code
  # - name: 'gcr.io/cloud-builders/docker'
  #   dir: 'nginx-flask-mongo/flask'
  #   entrypoint: 'pyflakes'
  #   args: ['.']

  # Lint with pyflakes
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install pyflakes && pyflakes nginx-flask-mongo/flask/*.py'

  # Build the Nginx frontend image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'nginx-flask-mongo'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-frontend:$COMMIT_SHA', '-f', 'nginx.Dockerfile', '.']

  # Push the images to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-frontend:$COMMIT_SHA']

  # Apply Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'nginx-flask-mongo/kubernetes.yaml']

  # Export logs to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args: ['cp', 'gs://440019-cloud-build-logging/$BUILD_ID.log']



options:
  logging: CLOUD_LOGGING_ONLY
