steps:
  # Build the Flask backend image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'nginx-flask-mongo/flask'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-backend:latest', '.']

  # Lint with pyflakes
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'pip install pyflakes && pyflakes nginx-flask-mongo/flask/*.py'

  # Build the Nginx frontend image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'nginx-flask-mongo/nginx'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nginx-frontend:latest', '-f', 'nginx.Dockerfile', '.']

  # Push the images to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-backend:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nginx-frontend:latest']

  # Apply Kubernetes manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'nginx-flask-mongo/kubernetes.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_REGION=${_CLOUDSDK_COMPUTE_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_COMPUTE_CLUSTER}'

options:
  logging: CLOUD_LOGGING_ONLY
